### ISSUE TITLE
Cannot retrive pretrained checkpoints

### ISSUE THREAD

**Issue by bartn8** [heudiasyc/ALED#1]
Dear Authors,
Unfortunately, I cannot access to pre-trained checkpoints using the suggested command:

```bash
git lfs pull
```
It gives me the following error:

```
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/heudiasyc/ALED.git/info/lfs'
```

Thanks

**Comment by vbrebion** [comment]
Hi!

Thank you very much for your interest in our work, and for letting us know about this issue!

I have just made the pre-trained weights available on the dataset platform of the lab.
They should be available for download here: <https://datasets.hds.utc.fr/share/V3LG5Dwa5OaJWaB>

Do not hesitate to confirm me if you can download them using the link above.
If this is the case, I will remove the weights from this repository, and update the README to add the new link.

Best,
Vincent

**Comment by bartn8** [comment]
Thanks it's working

**Comment by vbrebion** [comment]
Great to hear!

As promised, the weights were removed from the repo and the documentation was updated: https://github.com/heudiasyc/ALED/commit/6c8cfb9c4d958efabdcd9ebe8db4b0640d03c809

Thanks again for notifying us!

Best,
Vincent
